stockTab=Stock booking
warehouseId=Return warehouse ID
storageLocationId=Return storage location ID
reasonId=Stock movement reason
reasonDefect=Outgoing defect
reasonRubbish=Outgoing rubbish
reasonComplaint=Outgoing complaint
reasonCorrection=Outgoing correction
