stockTab=Bestandsausbuchung
warehouseId=ID des Retourenlagers
storageLocationId=ID des Retouren-Lagerorts
reasonId=Buchungsgrund
reasonDefect=Warenausgang Defekt
reasonRubbish=Warenausgang Ausschuss
reasonComplaint=Warenausgang Reklamation
reasonCorrection=Warenausgang Korrektur
